### ISSUE TITLE
Login problem 

### ISSUE THREAD

**Issue by yeasin6152** [ntkhang03/Goat-Bot-V2#89]
I opened a new Facebook ID, but I can't login to the bot, it shows an error, Login with cookies, but maximum 1 hour and then error again error is 

Login with email & password...
15:04:09 28/05/2024  ACCOUNT INFO: Email: ****, I_User: (empty)
15:04:33 28/05/2024  LOGIN FACEBOOK: An error occurred while signing in
15:04:33 28/05/2024  LOGIN FACEBOOK: Can't login to Facebook, please login to your account to check and fix this problem
15:04:33 28/05/2024  LOGIN FACEBOOK: LOGIN_FAILED: Can't login to Facebook, please login to your account to check and fix this problem
    at ⵂⴰⵀⵎ.<computed>.<computed>.program_ (/root/bot/login/getFbstate1.js:1:116511)
    at ⵂⴰⵀⵎ.<computed>.<computed>.<computed>.<computed> [as nextStep_] (/root/bot/login/getFbstate1.js:1:102352)
    at ⵂⴰⵀⵎ.<computed>.<computed>.<computed>.<computed> [as next_] (/root/bot/login/getFbstate1.js:1:100141)
    at <computed> [as next] (/root/bot/login/getFbstate1.js:1:103628)
    at ⵂⵀⵕⵄ (/root/bot/login/getFbstate1.js:1:104164)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by PhillipM18** [comment]
try to change useragent in config.json
